# Generated by Django 2.2 on 2019-04-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.PositiveIntegerField(unique=True, verbose_name='cedula')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('dedicacion', models.CharField(choices=[('EXC', 'Exclusiva'), ('TC', 'Tiempo Completo'), ('MT', 'Medio Tiempo'), ('TCV', 'Tiempo Convencional')], default='TC', max_length=5, verbose_name='Dedicacion')),
                ('categoria', models.CharField(choices=[('Titular', 'Titular'), ('Asociado', 'Asociado'), ('Agregado', 'Agregado'), ('Asistente', 'Asistente'), ('Instructor', 'Instructor')], default='Instructor', max_length=10, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('Ordinario', 'Ordinario'), ('Contratado', 'Contratado')], default='Contratado', max_length=15, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Postgrados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Pregrado')),
            ],
            options={
                'verbose_name': 'Postgrado',
                'verbose_name_plural': 'Postgrados',
            },
        ),
        migrations.CreateModel(
            name='Pregrados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Pregrado')),
            ],
            options={
                'verbose_name': 'Pregrado',
                'verbose_name_plural': 'Pregrados',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Telefono')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
            },
        ),
        migrations.CreateModel(
            name='PregradosDocente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('pregrado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docentes.Pregrados')),
            ],
            options={
                'verbose_name': 'Pregrado',
                'verbose_name_plural': 'Pregrados',
            },
        ),
        migrations.CreateModel(
            name='PostgradosDocente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('pregrado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docentes.Pregrados')),
            ],
            options={
                'verbose_name': 'Postgrado',
                'verbose_name_plural': 'Postgrados',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
