# Generated by Django 2.2 on 2020-01-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('dedicacion', models.CharField(choices=[('EXC', 'Exclusiva'), ('TC', 'Tiempo Completo'), ('MT', 'Medio Tiempo'), ('TCV', 'Tiempo Convencional')], default='TC', max_length=5, verbose_name='Dedicación')),
                ('categoria', models.CharField(choices=[('Titular', 'Titular'), ('Asociado', 'Asociado'), ('Agregado', 'Agregado'), ('Asistente', 'Asistente'), ('Instructor', 'Instructor')], default='Instructor', max_length=10, verbose_name='Categoría')),
                ('status', models.CharField(choices=[('Ordinario', 'Ordinario'), ('Contratado', 'Contratado')], default='Contratado', max_length=15, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Telefono')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.Docentes')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.Docentes')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
