# Generated by Django 2.2.4 on 2020-01-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_auto_20191111_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='categoria',
            field=models.CharField(choices=[('Titular', 'Titular'), ('Asociado', 'Asociado'), ('Agregado', 'Agregado'), ('Asistente', 'Asistente'), ('Instructor', 'Instructor')], default='Instructor', max_length=10, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='cedula',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='dedicacion',
            field=models.CharField(choices=[('EXC', 'Exclusiva'), ('TC', 'Tiempo Completo'), ('MT', 'Medio Tiempo'), ('TCV', 'Tiempo Convencional')], default='TC', max_length=5, verbose_name='Dedicación'),
        ),
    ]
