# Generated by Django 2.2 on 2020-01-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo/Nombre')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo/Nombre')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantaFisica.Edificio')),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
                'ordering': ('edificio',),
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo/Nombre')),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantaFisica.Piso')),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salones',
            },
        ),
    ]
