# Generated by Django 2.2 on 2020-01-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantaFisica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piso',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Codigo/Nombre'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Codigo/Nombre'),
        ),
    ]
