# Generated by Django 2.2 on 2020-01-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantaFisica', '0002_auto_20200107_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edificio',
            options={'ordering': ('codigo',), 'verbose_name': 'Edificio', 'verbose_name_plural': 'Edificios'},
        ),
        migrations.AlterModelOptions(
            name='piso',
            options={'ordering': ('edificio',), 'verbose_name': 'Piso', 'verbose_name_plural': 'Pisos'},
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Salon', 'verbose_name_plural': 'Salones'},
        ),
    ]
