# Generated by Django 2.2 on 2019-04-30 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('uni_credi', models.CharField(max_length=10, verbose_name='Unidad de Credito')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='codigo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('eje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.Eje')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
    ]
