# Generated by Django 2.2 on 2020-01-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera', '0001_initial'),
        ('docentes', '0001_initial'),
        ('plantaFisica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MallaUCEPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secciones', models.IntegerField(verbose_name='secciones')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('turno', models.CharField(choices=[('diurno', 'Diurno'), ('nocturno', 'Nocturno')], default='Diurno', max_length=20, null=True, verbose_name='Turno')),
                ('multiplicador', models.FloatField(blank=True, default=0, null=True, verbose_name='Multiplicador')),
                ('grupos', models.BooleanField(default=False, verbose_name='Grupos')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion_malla_periodo', to='planificacion.MallaUCEPeriodo')),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='SeccionPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_teoricas', models.FloatField(blank=True, default=0, null=True, verbose_name='Horas Teoricas')),
                ('horas_practicas', models.FloatField(blank=True, default=0, null=True, verbose_name='Horas Practicas')),
                ('docentes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seccion_periodo_docente', to='docentes.Docentes')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.Seccion')),
                ('suplente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seccion_periodo_docente_suplente', to='docentes.Docentes')),
                ('unidad_curricular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrera.UnidadCurricular')),
            ],
        ),
        migrations.AddField(
            model_name='mallauceperiodo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malla_periodo_p', to='planificacion.Periodo'),
        ),
        migrations.AddField(
            model_name='mallauceperiodo',
            name='trimestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrera.SubSubEstructura'),
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=20, null=True, verbose_name='Dia')),
                ('hora', models.CharField(blank=True, choices=[('1', '07:00 a 07:45'), ('2', '07:45 a 08:30'), ('3', '08:40 a 09:25'), ('4', '09:25 a 10:10'), ('5', '10:20 a 11:05'), ('6', '11:05 a 11:50'), ('7', '11:50 a 12:45'), ('8', '12:45 a 01:30'), ('9', '01:30 a 02:25'), ('10', '02:25 a 03:10'), ('11', '03:10 a 03:55'), ('12', '04:05 a 04:50'), ('13', '04:50 a 05:35'), ('14', '05:45 a 06:30')], max_length=20, null=True, verbose_name='Hora')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plantaFisica.Salon')),
                ('seccion_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_seccion_periodo', to='planificacion.SeccionPeriodo')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ('hora',),
            },
        ),
    ]
