# Generated by Django 2.2 on 2019-04-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_subperiodo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subperiodo',
            name='duracion',
        ),
        migrations.AddField(
            model_name='periodo',
            name='codigo',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Codigo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subperiodo',
            name='subperiodos',
            field=models.IntegerField(default=1, verbose_name='Subperiodos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subperiodo',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='subperiodo2',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Codigo'),
        ),
    ]
