# Generated by Django 2.2 on 2019-04-30 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_auto_20190430_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='subperiodo',
            name='subperiodos',
        ),
        migrations.AddField(
            model_name='periodo',
            name='subperiodos',
            field=models.IntegerField(default=1, verbose_name='Subperiodos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subperiodo',
            name='duracion',
            field=models.IntegerField(default=1, verbose_name='Duración'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subperiodo2',
        ),
        migrations.AddField(
            model_name='periodo',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.Estructura'),
        ),
    ]
