# Generated by Django 2.2 on 2019-04-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0005_auto_20190430_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eje',
            old_name='Name',
            new_name='nombre',
        ),
    ]
