# Generated by Django 2.2 on 2019-04-30 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0007_auto_20190430_0308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materia',
            new_name='UnidadCurricular',
        ),
    ]
