# Generated by Django 2.2 on 2019-04-30 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0008_auto_20190430_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='MallaUCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_teoricas', models.FloatField(blank=True, default=0, null=True, verbose_name='Horas Teoricas')),
                ('horas_practicas', models.FloatField(blank=True, default=0, null=True, verbose_name='Horas Practicas')),
                ('malla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.Malla')),
                ('subperiodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.Subperiodo')),
                ('unidad_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.UnidadCurricular')),
            ],
        ),
    ]
