# Generated by Django 2.2 on 2019-04-30 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0010_mallauce_laboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(auto_now=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(auto_now=True, null=True, verbose_name='Fecha Fin')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('diurno', 'Diurno'), ('nocturno', 'Nocturno')], default='Diurno', max_length=20, null=True, verbose_name='Sexo')),
                ('multiplicador', models.FloatField(blank=True, default=0, null=True, verbose_name='Multiplicador')),
                ('grupos', models.BooleanField(default=False, verbose_name='Grupos')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.Kuai')),
            ],
        ),
    ]
