# Generated by Django 2.2 on 2019-04-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0011_kuai_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuai',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='kuai',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
    ]
