# Generated by Django 2.2 on 2019-04-30 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0012_auto_20190430_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='malla_u_c_e',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.MallaUCE'),
        ),
    ]
