# Generated by Django 2.2 on 2019-04-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0013_seccion_malla_u_c_e'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='malla_u_c_e',
        ),
        migrations.AddField(
            model_name='seccion',
            name='subperiodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.Subperiodo'),
        ),
    ]
