# Generated by Django 2.2 on 2019-04-30 03:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('planificacion', '0014_auto_20190430_0353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Periodo',
            new_name='Orion',
        ),
    ]
