# Generated by Django 2.2 on 2019-04-30 03:57

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('planificacion', '0015_auto_20190430_0355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kuai',
            new_name='Periodo',
        ),
    ]
