# Generated by Django 2.2 on 2019-04-30 04:00

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('planificacion', '0016_auto_20190430_0357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orion',
            new_name='Subestructura',
        ),
    ]
