# Generated by Django 2.2 on 2019-04-30 04:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('planificacion', '0017_auto_20190430_0400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subperiodo',
            new_name='SubSubEstructura',
        ),
        migrations.RenameField(
            model_name='mallauce',
            old_name='subperiodo',
            new_name='sub_sub_estructura',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='subperiodo',
            new_name='Subestructura',
        ),
    ]
