# Generated by Django 2.2 on 2019-04-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0018_auto_20190430_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='codigo',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Codigo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(default=1, max_length=200, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
