# Generated by Django 2.2 on 2019-04-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0019_auto_20190430_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seccion',
            old_name='Subestructura',
            new_name='sub_sub_estructura',
        ),
    ]
