# Generated by Django 2.2 on 2019-04-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0020_auto_20190430_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='turno',
            field=models.CharField(choices=[('diurno', 'Diurno'), ('nocturno', 'Nocturno')], default='Diurno', max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
