# Generated by Django 2.2 on 2019-05-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0021_auto_20190430_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadcurricular',
            name='eje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.Eje'),
        ),
    ]
