# Generated by Django 2.2 on 2019-05-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0022_auto_20190504_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsubestructura',
            old_name='periodo',
            new_name='subestructura',
        ),
    ]
