# Generated by Django 2.2 on 2019-05-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0023_auto_20190504_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='mallauce',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.Periodo'),
        ),
    ]
