# Generated by Django 2.2 on 2019-05-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0024_mallauce_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mallauce',
            name='periodo',
        ),
    ]
