# Generated by Django 2.2 on 2019-05-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0025_remove_mallauce_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='malla_uce',
            field=models.ManyToManyField(blank=True, to='planificacion.MallaUCE'),
        ),
    ]
