# Generated by Django 2.2 on 2019-05-04 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0027_auto_20190504_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='sub_sub_estructura',
        ),
        migrations.AddField(
            model_name='periodo',
            name='malla_uce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.MallaUCE'),
        ),
    ]
