# Generated by Django 2.2 on 2019-05-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0028_auto_20190504_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='malla_uce',
        ),
        migrations.AddField(
            model_name='periodo',
            name='malla_uce',
            field=models.ManyToManyField(blank=True, to='planificacion.MallaUCE'),
        ),
    ]
