# Generated by Django 2.2 on 2019-05-04 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('planificacion', '0029_auto_20190504_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='malla_uce',
        ),
        migrations.CreateModel(
            name='MallaUCEPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secciones', models.IntegerField(verbose_name='secciones')),
                ('Periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.Periodo')),
                ('malla_uce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.MallaUCE')),
            ],
        ),
    ]
