# Generated by Django 2.2 on 2019-05-10 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0006_auto_20190510_0125'),
        ('planificacion', '0031_auto_20190510_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='mallauceperiodo',
            name='malla_uce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrera.MallaUCE'),
        ),
    ]
