# Generated by Django 2.2 on 2019-05-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0033_auto_20190512_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mallauceperiodo',
            old_name='Periodo',
            new_name='periodo',
        ),
        migrations.RenameField(
            model_name='mallauceperiodo',
            old_name='subsubestructura',
            new_name='trimestre',
        ),
    ]
