# Generated by Django 2.2 on 2019-05-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0034_auto_20190512_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.MallaUCEPeriodo'),
        ),
    ]
