# Generated by Django 2.2 on 2019-05-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0035_auto_20190512_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Codigo'),
        ),
    ]
