# Generated by Django 2.2 on 2019-05-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0008_auto_20190512_1520'),
        ('docentes', '0001_initial'),
        ('planificacion', '0036_auto_20190512_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docentes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docentes.Docentes')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.Seccion')),
                ('unidad_curricular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrera.UnidadCurricular')),
            ],
        ),
    ]
