# Generated by Django 2.2 on 2019-05-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0037_seccionperiodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seccion_malla_periodo', to='planificacion.MallaUCEPeriodo'),
        ),
    ]
