# Generated by Django 2.2 on 2019-06-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0038_auto_20190527_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterField(
            model_name='seccion',
            name='turno',
            field=models.CharField(choices=[('diurno', 'Diurno'), ('nocturno', 'Nocturno')], default='Diurno', max_length=20, null=True, verbose_name='Turno'),
        ),
    ]
