# Generated by Django 2.2 on 2019-10-27 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0039_auto_20190610_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mallauceperiodo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.Periodo'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion_malla_periodo', to='planificacion.MallaUCEPeriodo'),
        ),
        migrations.AlterField(
            model_name='seccionperiodo',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.Seccion'),
        ),
    ]
