# Generated by Django 2.2 on 2019-10-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0042_auto_20191027_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionperiodo',
            name='docentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docentes.Docentes'),
        ),
    ]
