# Generated by Django 2.2 on 2019-11-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0043_auto_20191027_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionperiodo',
            name='horas_practicas',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Horas Practicas'),
        ),
        migrations.AddField(
            model_name='seccionperiodo',
            name='horas_teoricas',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Horas Teoricas'),
        ),
        migrations.AlterField(
            model_name='mallauceperiodo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malla_periodo_p', to='planificacion.Periodo'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='seccionperiodo',
            name='docentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seccion_periodo_docente', to='docentes.Docentes'),
        ),
    ]
