# Generated by Django 2.2 on 2019-11-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0044_auto_20191110_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Codigo'),
        ),
    ]
