# Generated by Django 2.2 on 2020-01-07 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantaFisica', '0001_initial'),
        ('planificacion', '0046_seccionperiodo_suplente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ('codigo',)},
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default='Dia', max_length=20, null=True, verbose_name='Dia')),
                ('hora', models.CharField(choices=[('nocturno', 'Nocturno')], default='Hora', max_length=20, null=True, verbose_name='Hora')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantaFisica.Salon')),
                ('seccion_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.SeccionPeriodo')),
            ],
        ),
    ]
