# Generated by Django 2.2 on 2020-01-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0047_auto_20200107_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarios',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterField(
            model_name='horarios',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default=1, max_length=20, verbose_name='Dia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horarios',
            name='hora',
            field=models.CharField(choices=[('07:00 a 07:45', '07:00 a 07:45'), ('07:45 a 08:30', '07:45 a 08:30'), ('08:40 a 09:25', '08:40 a 09:25'), ('09:25 a 10:10', '09:25 a 10:10'), ('10:20 a 11:05', '10:20 a 11:05'), ('11:05 a 11:50', '11:05 a 11:50'), ('11:50 a 12:45', '11:50 a 12:45'), ('12:45 a 01:30', '12:45 a 01:30'), ('01:30 a 02:25', '01:30 a 02:25'), ('02:25 a 03:10', '02:25 a 03:10'), ('03:10 a 03:55', '03:10 a 03:55'), ('04:05 a 04:50', '04:05 a 04:50'), ('04:50 a 05:35', '04:50 a 05:35'), ('05:45 a 06:30', '05:45 a 06:30')], default=1, max_length=20, verbose_name='Hora'),
            preserve_default=False,
        ),
    ]
