# Generated by Django 2.2 on 2020-01-13 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0048_auto_20200108_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='hora',
            field=models.CharField(choices=[(1, '07:00 a 07:45'), (2, '07:45 a 08:30'), (3, '08:40 a 09:25'), (4, '09:25 a 10:10'), (5, '10:20 a 11:05'), (6, '11:05 a 11:50'), (7, '11:50 a 12:45'), (8, '12:45 a 01:30'), (9, '01:30 a 02:25'), (10, '02:25 a 03:10'), (11, '03:10 a 03:55'), (12, '04:05 a 04:50'), (13, '04:50 a 05:35'), (14, '05:45 a 06:30')], max_length=20, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='seccion_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_seccion_periodo', to='planificacion.SeccionPeriodo'),
        ),
    ]
