# Generated by Django 2.2 on 2020-01-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0051_auto_20200114_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plantaFisica.Salon'),
        ),
    ]
