# Generated by Django 2.2.4 on 2020-01-16 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0052_auto_20200114_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarios',
            options={'ordering': ('hora',), 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
    ]
