# Generated by Django 2.2 on 2019-05-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subestructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('subperiodos', models.IntegerField(verbose_name='Subperiodos')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubEstructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('duracion', models.IntegerField(verbose_name='Duración')),
                ('subestructura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrera.Subestructura')),
            ],
        ),
    ]
