# Generated by Django 2.2 on 2020-01-18 19:31

import audit.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha', models.DateField(auto_now=True, null=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Subestructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('subperiodos', models.IntegerField(verbose_name='Subperiodos')),
                ('malla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malla_subestructura', to='carrera.Malla')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('uni_credi', models.CharField(max_length=10, verbose_name='Unidad de Credito')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='codigo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
            bases=(audit.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubSubEstructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('duracion', models.IntegerField(verbose_name='Duración')),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrera.SubSubEstructura')),
                ('subestructura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tt', to='carrera.Subestructura')),
            ],
        ),
        migrations.CreateModel(
            name='MallaUCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_teoricas', models.FloatField(blank=True, default=0, null=True, verbose_name='Horas Teoricas')),
                ('horas_practicas', models.FloatField(blank=True, default=0, null=True, verbose_name='Horas Practicas')),
                ('laboratorio', models.BooleanField(default=False)),
                ('malla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrera.Malla')),
                ('sub_sub_estructura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malla_uce_ss_estruct', to='carrera.SubSubEstructura')),
                ('unidad_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malla_unidad_credito', to='carrera.UnidadCurricular')),
            ],
        ),
    ]
