# Generated by Django 2.2 on 2019-05-09 22:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subestructura',
            new_name='CSubestructura',
        ),
        migrations.RenameModel(
            old_name='SubSubEstructura',
            new_name='CSubSubEstructura',
        ),
    ]
