# Generated by Django 2.2 on 2019-05-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0002_auto_20190509_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='csubsubestructura',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrera.CSubSubEstructura'),
        ),
    ]
