# Generated by Django 2.2 on 2019-05-09 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0003_csubsubestructura_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csubsubestructura',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrera.CSubSubEstructura'),
        ),
    ]
