# Generated by Django 2.2 on 2019-05-10 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0004_auto_20190509_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=100, verbose_name='Trayecto y Trimestre')),
                ('fecha', models.DateField(auto_now=True, null=True, verbose_name='fecha')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('uni_credi', models.CharField(max_length=10, verbose_name='Unidad de Credito')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='codigo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='MallaUCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_teoricas', models.FloatField(blank=True, default=0, null=True, verbose_name='Horas Teoricas')),
                ('horas_practicas', models.FloatField(blank=True, default=0, null=True, verbose_name='Horas Practicas')),
                ('laboratorio', models.BooleanField(default=False)),
                ('malla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrera.Malla')),
                ('sub_sub_estructura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrera.CSubSubEstructura')),
                ('unidad_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrera.UnidadCurricular')),
            ],
        ),
    ]
