# Generated by Django 2.2 on 2019-05-10 01:25

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('carrera', '0005_malla_mallauce_unidadcurricular'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSubestructura',
            new_name='Subestructura',
        ),
        migrations.RenameModel(
            old_name='CSubSubEstructura',
            new_name='SubSubEstructura',
        ),
    ]
