# Generated by Django 2.2 on 2019-05-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0006_auto_20190510_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='subestructura',
            name='malla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrera.Malla'),
        ),
        migrations.AlterField(
            model_name='mallauce',
            name='sub_sub_estructura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malla_uce_sub_sub_estructura', to='carrera.SubSubEstructura'),
        ),
    ]
