# Generated by Django 2.2 on 2019-05-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0007_auto_20190512_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subestructura',
            name='malla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malla_subestructura', to='carrera.Malla'),
        ),
    ]
