# Generated by Django 2.2 on 2019-05-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0008_auto_20190512_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malla',
            name='cod',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='malla',
            name='fecha',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='mallauce',
            name='unidad_credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malla_unidad_credito', to='carrera.UnidadCurricular'),
        ),
    ]
