# Generated by Django 2.2 on 2019-06-10 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0009_auto_20190527_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubestructura',
            name='subestructura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tt', to='carrera.Subestructura'),
        ),
    ]
