# Generated by Django 2.2 on 2019-10-27 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0010_auto_20190610_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mallauce',
            name='sub_sub_estructura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malla_uce_ss_estruct', to='carrera.SubSubEstructura'),
        ),
    ]
